apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentservice
  template:
    metadata:
      labels:
        app: contentservice
    spec:
      containers:
        - name: postgres-content
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-content
spec:
  selector:
    app: contentservice
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

