apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentservice
  template:
    metadata:
      labels:
        app: contentservice
    spec:
      containers:
        - name: postgres-content
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
