apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: contentservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer


